site_name: pylovo
site_description: 'A python tool for low-voltage distribution grid generation'
repo_name: tum-ens/pylovo
repo_url: https://gitlab.lrz.de/tum-ens/pylovo
theme:
  name: material
  logo: Logo_of_the_Technical_University_of_Munich.svg
  palette:
    primary: white

plugins:
  - mkdocstrings
  - autorefs
  - search

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Advanced Installation: installation.md
  - Usage: usage.md
  - References: ref.md

extra:
  search:
    language: en
    tokenization:
      letter_pattern: "\\w+"
      min_token_length: 2