import warnings

from classification.clustering.cluster_settings import print_parameters_for_clustering_for_classification_version

warnings.filterwarnings('ignore')

print_parameters_for_clustering_for_classification_version()
