# Database schema - table structure
from pylovo.config_loader import TARGET_EPSG, FEEDER_CABLES


INFDB_OPTIONAL_TABLES = {"res", "oth", "ways"}



CREATE_QUERIES = {
    "version": """CREATE TABLE IF NOT EXISTS pylovo.version (
        version_id varchar(10) PRIMARY KEY,
        version_comment varchar, 
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        generation_parameters jsonb
    );
    ALTER TABLE pylovo.version ADD COLUMN IF NOT EXISTS generation_parameters jsonb;
    """,
    "equipment_data": """
   CREATE TABLE IF NOT EXISTS pylovo.equipment_data(
       version_id       varchar(10)  NOT NULL,
       name             varchar(100) NOT NULL,
       s_max_kva        integer,
       max_i_a          integer,
       r_mohm_per_km    integer,
       x_mohm_per_km    integer,
       z_mohm_per_km    integer,
       cost_eur         integer,
       typ              varchar(50),
       grid_role        varchar(50),
       CONSTRAINT equipment_data_pkey PRIMARY KEY (version_id, name),
       CONSTRAINT fk_equipment_data_version
           FOREIGN KEY (version_id)
               REFERENCES pylovo.version (version_id)
               ON DELETE CASCADE
   )
    """,
    "classification_version": """
    CREATE TABLE IF NOT EXISTS pylovo.classification_version (
        classification_id integer NOT NULL,
        classification_version_comment varchar, 
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        classification_region varchar,
        CONSTRAINT classification_pkey PRIMARY KEY (classification_id)
    )
    """,
    "postcode": """
    CREATE TABLE IF NOT EXISTS pylovo.postcode (
        postcode_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        plz integer UNIQUE NOT NULL,
        note varchar,
        qkm double precision,
        population integer,
        geom geometry(MultiPolygon,{TARGET_EPSG}),
        CONSTRAINT "plz-5stellig_pkey" PRIMARY KEY (postcode_id)
    )
    """,
    "postcode_result": """
    CREATE TABLE IF NOT EXISTS pylovo.postcode_result (   
        version_id varchar(10) NOT NULL,
        postcode_result_plz integer NOT NULL,
        geom geometry(MultiPolygon,{TARGET_EPSG}),
        house_distance double precision,
        avg_households_per_building double precision,
        settlement_type integer,
        
        CONSTRAINT "postcode_result_pkey" PRIMARY KEY (version_id, postcode_result_plz),
        CONSTRAINT fk_postcode_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES pylovo.version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_postcode_result_plz
            FOREIGN KEY (postcode_result_plz)
            REFERENCES pylovo.postcode (plz)
            ON DELETE CASCADE
    )
    """,
    "grid_result": """
    CREATE TABLE IF NOT EXISTS pylovo.grid_result (
        grid_result_id SERIAL PRIMARY KEY,
        version_id varchar(10) NOT NULL,
        kcid integer NOT NULL,
        bcid integer NOT NULL,
        plz integer NOT NULL,
        transformer_rated_power bigint,
        transformer_equipment_name varchar(100),
        transformer_description varchar(100),
        model_status integer,
        ont_vertice_id bigint,
        power_flow_status varchar(32),
        grid json,
        CONSTRAINT cluster_identifier UNIQUE (version_id, kcid, bcid, plz),
        CONSTRAINT unique_grid_result_id_version_id UNIQUE (version_id, grid_result_id),
        CONSTRAINT fk_grid_result_version_id_plz
            FOREIGN KEY (version_id, plz)
            REFERENCES pylovo.postcode_result (version_id, postcode_result_plz)
            ON DELETE CASCADE,
        CONSTRAINT fk_grid_result_transformer_equipment
            FOREIGN KEY (version_id, transformer_equipment_name)
            REFERENCES pylovo.equipment_data(version_id, name)
            ON DELETE SET NULL
    );
    CREATE INDEX IF NOT EXISTS idx_grid_result_version_id_plz_bcid_kcid
    ON pylovo.grid_result (version_id, plz, bcid, kcid);
    """,
    "lines_result": """
    CREATE TABLE IF NOT EXISTS pylovo.lines_result (
        lines_result_id SERIAL PRIMARY KEY,
        grid_result_id bigint NOT NULL,
        geom geometry(LineString,{TARGET_EPSG}),
        line_name varchar(50),
        std_type varchar(50),
        from_bus integer,
        to_bus integer,
        parallel integer,
        length_km double precision,
        feeder_section_id integer,
        CONSTRAINT fk_lines_result_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    );
    ALTER TABLE pylovo.lines_result ADD COLUMN IF NOT EXISTS feeder_section_id integer;
    CREATE INDEX IF NOT EXISTS idx_lines_result_grid_result_id
    ON pylovo.lines_result (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_lines_result_grid_section_id
    ON pylovo.lines_result (grid_result_id, feeder_section_id)
    """,
    "lines_result_helper": """
    CREATE TABLE IF NOT EXISTS pylovo.lines_result_helper (
        lines_result_helper_id SERIAL PRIMARY KEY,
        source_lines_result_id bigint NOT NULL,
        grid_result_id bigint NOT NULL,
        geom geometry(Geometry,{TARGET_EPSG}),
        line_name varchar(50),
        std_type varchar(50),
        from_bus integer,
        to_bus integer,
        parallel integer,
        length_km double precision,
        helper_type varchar(50),
        CONSTRAINT fk_lines_result_helper_source_line
            FOREIGN KEY (source_lines_result_id)
            REFERENCES pylovo.lines_result (lines_result_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_lines_result_helper_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_lines_result_helper_grid_result_id
    ON pylovo.lines_result_helper (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_lines_result_helper_source_line
    ON pylovo.lines_result_helper (source_lines_result_id);
    CREATE INDEX IF NOT EXISTS idx_lines_result_helper_geom
    ON pylovo.lines_result_helper USING gist (geom)
    """,
    "split_points": """
    CREATE TABLE IF NOT EXISTS pylovo.split_points (
        split_point_id SERIAL PRIMARY KEY,
        grid_result_id bigint NOT NULL,
        split_bus integer NOT NULL,
        outgoing_count integer,
        split_type varchar(50),
        geom geometry(Point,{TARGET_EPSG}),
        CONSTRAINT fk_split_points_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE,
        CONSTRAINT uq_split_points_grid_bus
            UNIQUE (grid_result_id, split_bus)
    );
    CREATE INDEX IF NOT EXISTS idx_split_points_grid_result_id
    ON pylovo.split_points (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_split_points_geom
    ON pylovo.split_points USING gist (geom)
    """,
    "lines_result_view": """
    DROP MATERIALIZED VIEW IF EXISTS pylovo.lines_result_with_grid CASCADE;
    CREATE TABLE IF NOT EXISTS pylovo.lines_result_view (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        is_helper boolean NOT NULL,
        source_lines_result_id bigint,
        helper_type varchar(50),
        grid_result_id bigint NOT NULL,
        geom geometry(Geometry,{TARGET_EPSG}),
        line_name varchar(50),
        std_type varchar(50),
        from_bus integer,
        to_bus integer,
        parallel integer,
        length_km double precision,
        feeder_section_id integer,
        version_id varchar(10) NOT NULL,
        kcid integer NOT NULL,
        bcid integer NOT NULL,
        plz integer NOT NULL,
        CONSTRAINT fk_lines_result_view_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_lines_result_view_source_line
            FOREIGN KEY (source_lines_result_id)
            REFERENCES pylovo.lines_result (lines_result_id)
            ON DELETE CASCADE
    );
    ALTER TABLE pylovo.lines_result_view ADD COLUMN IF NOT EXISTS feeder_section_id integer;
    CREATE INDEX IF NOT EXISTS idx_lines_result_view_grid_result_id
    ON pylovo.lines_result_view (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_lines_result_view_version_plz
    ON pylovo.lines_result_view (version_id, plz);
    CREATE INDEX IF NOT EXISTS idx_lines_result_view_grid_section_id
    ON pylovo.lines_result_view (grid_result_id, feeder_section_id);
    CREATE INDEX IF NOT EXISTS idx_lines_result_view_geom
    ON pylovo.lines_result_view USING gist (geom)
    """,
    "consumer_categories": """
    CREATE TABLE IF NOT EXISTS pylovo.consumer_categories (
        consumer_category_id integer PRIMARY KEY,
        definition varchar(30) UNIQUE NOT NULL,
        peak_load double precision,
        yearly_consumption double precision,
        peak_load_per_m2 double precision,
        yearly_consumption_per_m2 double precision,
        sim_factor double precision NOT NULL
    )
    """,
    "buildings_result": """
    DROP MATERIALIZED VIEW IF EXISTS pylovo.buildings_result_with_grid CASCADE;
    DO $$
    BEGIN
        IF to_regclass('pylovo.buildings_result') IS NOT NULL THEN
            ALTER TABLE pylovo.buildings_result DROP CONSTRAINT IF EXISTS fk_buildings_result_type;
            ALTER TABLE pylovo.buildings_result DROP CONSTRAINT IF EXISTS buildings_result_pkey;

            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'osm_id')
               AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'objectid') THEN
                ALTER TABLE pylovo.buildings_result RENAME COLUMN osm_id TO objectid;
            END IF;

            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'area')
               AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'floor_area') THEN
                ALTER TABLE pylovo.buildings_result RENAME COLUMN area TO floor_area;
            END IF;

            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'floors')
               AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'floor_number') THEN
                ALTER TABLE pylovo.buildings_result RENAME COLUMN floors TO floor_number;
            END IF;

            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'households_per_building')
               AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'households') THEN
                ALTER TABLE pylovo.buildings_result RENAME COLUMN households_per_building TO households;
            END IF;

            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'center')
               AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'pylovo' AND table_name = 'buildings_result' AND column_name = 'centroid') THEN
                ALTER TABLE pylovo.buildings_result RENAME COLUMN center TO centroid;
            END IF;

        END IF;
    END $$;

    CREATE TABLE IF NOT EXISTS pylovo.buildings_result (
        version_id varchar(10) NOT NULL,
        objectid text NOT NULL,
        grid_result_id bigint NOT NULL,
        id integer,
        feature_id integer,
        height double precision,
        floor_area double precision,
        floor_number integer,
        residential_floor_area double precision,
        nonresidential_floor_area double precision,
        nonresidential_use varchar(30),
        mix_score double precision,
        mix_rule text,
        mix_confidence text,
        building_use text,
        building_use_id text,
        building_type text,
        type varchar(30),
        occupants integer,
        households integer,
        construction_year text,
        postcode integer,
        address_street_id bigint,
        street text,
        house_number text,
        geom geometry(MultiPolygon,{TARGET_EPSG}),
        centroid geometry(Point,{TARGET_EPSG}),
        gemeindeschluessel text,
        changelog_id bigint,
        assigned_way_id text,
        residential_peak_load_in_kw double precision,
        nonresidential_peak_load_in_kw double precision,
        nonresidential_mv_direct boolean NOT NULL DEFAULT false,
        peak_load_in_kw double precision,
        vertice_id integer,
        connection_point integer,
        agg_connection_point integer,
        CONSTRAINT buildings_result_pkey PRIMARY KEY (version_id, objectid),
        CONSTRAINT fk_buildings_result_grid_result
            FOREIGN KEY (version_id, grid_result_id)
            REFERENCES pylovo.grid_result (version_id, grid_result_id)
            ON DELETE CASCADE
    );
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS id integer;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS feature_id integer;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS objectid text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS height double precision;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS floor_area double precision;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS floor_number integer;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS residential_floor_area double precision;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS nonresidential_floor_area double precision;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS nonresidential_use varchar(30);
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS mix_score double precision;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS mix_rule text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS mix_confidence text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS building_use text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS building_use_id text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS building_type text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS type varchar(30);
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS occupants integer;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS households integer;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS construction_year text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS postcode integer;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS address_street_id bigint;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS street text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS house_number text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS geom geometry(MultiPolygon,{TARGET_EPSG});
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS centroid geometry(Point,{TARGET_EPSG});
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS gemeindeschluessel text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS changelog_id bigint;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS assigned_way_id text;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS residential_peak_load_in_kw double precision;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS nonresidential_peak_load_in_kw double precision;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS nonresidential_mv_direct boolean NOT NULL DEFAULT false;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS peak_load_in_kw double precision;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS vertice_id integer;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS connection_point integer;
    ALTER TABLE pylovo.buildings_result ADD COLUMN IF NOT EXISTS agg_connection_point integer;
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'buildings_result_pkey'
              AND conrelid = 'pylovo.buildings_result'::regclass
        ) THEN
            ALTER TABLE pylovo.buildings_result ADD CONSTRAINT buildings_result_pkey PRIMARY KEY (version_id, objectid);
        END IF;
    END $$;
    CREATE INDEX IF NOT EXISTS idx_buildings_result_grid_result_id
    ON pylovo.buildings_result (grid_result_id);
    """,
    "municipal_register": """CREATE TABLE IF NOT EXISTS pylovo.municipal_register (
        plz integer,
        pop bigint,
        area double precision,
        lat double precision,
        lon double precision,
        ags bigint,
        name_city text,
        fed_state integer,
        regio7 integer,
        regio5 integer,
        pop_den double precision,
        CONSTRAINT municipal_register_pkey PRIMARY KEY (plz, ags)
    )
    """,
    "sample_set": """CREATE TABLE IF NOT EXISTS pylovo.sample_set (
        classification_id integer NOT NULL,
        plz integer NOT NULL,
        ags bigint,
        bin_no integer,
        bins double precision,
        perc_bin double precision,
        count double precision,
        perc double precision,
        CONSTRAINT sample_set_pkey PRIMARY KEY (classification_id, plz),
        CONSTRAINT fk_sample_set_classification_id
            FOREIGN KEY (classification_id)
            REFERENCES pylovo.classification_version (classification_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_sample_set_plz
            FOREIGN KEY (plz, ags)
            REFERENCES pylovo.municipal_register (plz, ags)
            ON DELETE CASCADE
    )
    """,
    "clustering_parameters": """CREATE TABLE IF NOT EXISTS pylovo.clustering_parameters (
        grid_result_id bigint PRIMARY KEY,
        no_connection_buses integer,
        no_branches integer,
        no_house_connections integer,
        no_house_connections_per_branch double precision,
        no_households integer,
        no_household_equ double precision,
        no_households_per_branch double precision,
        max_no_of_households_of_a_branch double precision,
        house_distance_km double precision,
        transformer_mva double precision,
        osm_trafo bool,
        max_trafo_dis double precision,
        avg_trafo_dis double precision,
        cable_length_km double precision,
        cable_len_per_house double precision,
        max_power_mw double precision,
        simultaneous_peak_load_mw double precision,
        resistance double precision,
        reactance double precision,
        ratio double precision,
        vsw_per_branch double precision,
        max_vsw_of_a_branch double precision,
        filtered boolean,
        CONSTRAINT fk_clustering_parameters_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
        "grid_parameters": """CREATE TABLE IF NOT EXISTS pylovo.grid_parameters (
        grid_result_id bigint PRIMARY KEY,
        power_flow_status varchar(32),
        feeder_lines integer,
        buildings_per_feeder double precision,
        graph_length double precision,
        avg_trafo_distance double precision,
        max_trafo_distance double precision,
        transformer_mva double precision,
        graph_resistance double precision,
        CONSTRAINT fk_grid_parameters_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "pandapower_bus": """
    CREATE TABLE IF NOT EXISTS pylovo.pandapower_bus (
        pandapower_bus_id SERIAL PRIMARY KEY,
        grid_result_id bigint NOT NULL,
        pp_index integer NOT NULL,
        name varchar(255),
        vn_kv double precision,
        type varchar(32),
        zone varchar(32),
        geo jsonb,
        in_service boolean,
        min_vm_pu double precision,
        max_vm_pu double precision,
        CONSTRAINT uq_pandapower_bus_grid_result_pp_index UNIQUE (grid_result_id, pp_index),
        CONSTRAINT fk_pandapower_bus_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_pandapower_bus_grid_result_id
    ON pylovo.pandapower_bus (grid_result_id);
    """,
    "pandapower_line": """
    CREATE TABLE IF NOT EXISTS pylovo.pandapower_line (
        pandapower_line_id SERIAL PRIMARY KEY,
        grid_result_id bigint NOT NULL,
        pp_index integer NOT NULL,
        name varchar(255),
        std_type varchar(100),
        from_bus integer,
        to_bus integer,
        length_km double precision,
        parallel integer,
        geo jsonb,
        in_service boolean,
        r_ohm_per_km double precision,
        x_ohm_per_km double precision,
        c_nf_per_km double precision,
        g_us_per_km double precision,
        max_i_ka double precision,
        df double precision,
        type varchar(32),
        CONSTRAINT uq_pandapower_line_grid_result_pp_index UNIQUE (grid_result_id, pp_index),
        CONSTRAINT fk_pandapower_line_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_pandapower_line_grid_result_id
    ON pylovo.pandapower_line (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_pandapower_line_from_to_bus
    ON pylovo.pandapower_line (from_bus, to_bus);
    """,
    "pandapower_trafo": """
    CREATE TABLE IF NOT EXISTS pylovo.pandapower_trafo (
        pandapower_trafo_id SERIAL PRIMARY KEY,
        grid_result_id bigint NOT NULL,
        pp_index integer NOT NULL,
        name varchar(255),
        std_type varchar(100),
        hv_bus integer,
        lv_bus integer,
        sn_mva double precision,
        vn_hv_kv double precision,
        vn_lv_kv double precision,
        vkr_percent double precision,
        vk_percent double precision,
        pfe_kw double precision,
        i0_percent double precision,
        shift_degree double precision,
        tap_side varchar(16),
        tap_neutral integer,
        tap_min integer,
        tap_max integer,
        tap_step_percent double precision,
        tap_pos integer,
        tap_phase_shifter boolean,
        parallel integer,
        in_service boolean,
        CONSTRAINT uq_pandapower_trafo_grid_result_pp_index UNIQUE (grid_result_id, pp_index),
        CONSTRAINT fk_pandapower_trafo_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_pandapower_trafo_grid_result_id
    ON pylovo.pandapower_trafo (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_pandapower_trafo_hv_lv_bus
    ON pylovo.pandapower_trafo (hv_bus, lv_bus);
    """,
    "pandapower_load": """
    CREATE TABLE IF NOT EXISTS pylovo.pandapower_load (
        pandapower_load_id SERIAL PRIMARY KEY,
        grid_result_id bigint NOT NULL,
        pp_index integer NOT NULL,
        name varchar(255),
        bus integer,
        p_mw double precision,
        q_mvar double precision,
        category varchar(30),
        load_units double precision,
        consumer_vertex bigint,
        const_z_percent double precision,
        const_i_percent double precision,
        sn_mva double precision,
        scaling double precision,
        in_service boolean,
        type varchar(64),
        controllable boolean,
        max_p_mw double precision,
        min_p_mw double precision,
        max_q_mvar double precision,
        min_q_mvar double precision,
        CONSTRAINT uq_pandapower_load_grid_result_pp_index UNIQUE (grid_result_id, pp_index),
        CONSTRAINT fk_pandapower_load_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    );
    ALTER TABLE pylovo.pandapower_load ADD COLUMN IF NOT EXISTS category varchar(30);
    ALTER TABLE pylovo.pandapower_load ADD COLUMN IF NOT EXISTS load_units double precision;
    ALTER TABLE pylovo.pandapower_load ADD COLUMN IF NOT EXISTS consumer_vertex bigint;
    CREATE INDEX IF NOT EXISTS idx_pandapower_load_grid_result_id
    ON pylovo.pandapower_load (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_pandapower_load_bus
    ON pylovo.pandapower_load (bus);
    """,
    "transformers": """CREATE TABLE IF NOT EXISTS pylovo.transformers (
        osm_id varchar PRIMARY KEY,
        area double precision,
        type varchar,
        transformer_rated_power integer,
        geom_type varchar,
        within_shopping boolean,
        osm boolean NOT NULL DEFAULT true,
        lod2 boolean NOT NULL DEFAULT false,
        lod2_objectid text,
        geom geometry(MultiPoint, {TARGET_EPSG})
    );
    ALTER TABLE pylovo.transformers ADD COLUMN IF NOT EXISTS osm boolean NOT NULL DEFAULT true;
    ALTER TABLE pylovo.transformers ADD COLUMN IF NOT EXISTS lod2 boolean NOT NULL DEFAULT false;
    ALTER TABLE pylovo.transformers ADD COLUMN IF NOT EXISTS lod2_objectid text;
    CREATE INDEX IF NOT EXISTS idx_transformers_geom
    ON pylovo.transformers USING gist (geom)
    """,
    "transformer_positions": """
    CREATE TABLE IF NOT EXISTS pylovo.transformer_positions (
        grid_result_id bigint PRIMARY KEY,
        geom geometry(Point,{TARGET_EPSG}),
        osm_id varchar,
        version_id varchar(10),
        "comment" varchar,
        osm boolean NOT NULL DEFAULT false,
        lod2 boolean NOT NULL DEFAULT false,
        lod2_objectid text,
        CONSTRAINT uq_tp_osm_v UNIQUE (osm_id, version_id),
        CONSTRAINT fk_tp_version_id
            FOREIGN KEY (version_id)
            REFERENCES pylovo.version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_tp_grid_result_id
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_tp_osm_id
            FOREIGN KEY (osm_id)
            REFERENCES pylovo.transformers (osm_id)
            ON DELETE CASCADE
    );
    ALTER TABLE pylovo.transformer_positions ADD COLUMN IF NOT EXISTS osm boolean NOT NULL DEFAULT false;
    ALTER TABLE pylovo.transformer_positions ADD COLUMN IF NOT EXISTS lod2 boolean NOT NULL DEFAULT false;
    ALTER TABLE pylovo.transformer_positions ADD COLUMN IF NOT EXISTS lod2_objectid text
    """,
    "transformer_classified": """
    CREATE TABLE IF NOT EXISTS pylovo.transformer_classified (
        grid_result_id bigint NOT NULL,
        geom geometry(Point,{TARGET_EPSG}),
        kmedoid_clusters integer,
        kmedoid_representative_grid bool,
        kmeans_clusters integer,
        kmeans_representative_grid bool,
        gmm_clusters integer,
        gmm_representative_grid bool,
        classification_id integer NOT NULL,
        CONSTRAINT pk_grid_result_id PRIMARY KEY (grid_result_id, classification_id),
        CONSTRAINT fk_transformer_classified_classification_id
            FOREIGN KEY (classification_id)
            REFERENCES pylovo.classification_version (classification_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_transformer_classified_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES pylovo.grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "ags_log": """
    CREATE TABLE IF NOT EXISTS pylovo.ags_log (
        ags bigint PRIMARY KEY
    )
    """,
    "ways": """
    CREATE TABLE IF NOT EXISTS pylovo.ways (
        clazz integer,
        source integer,
        target integer,
        cost double precision,
        reverse_cost double precision,
        geom geometry(LineString,{TARGET_EPSG}),
        way_id integer PRIMARY KEY
    )
    """,
    "ways_result": """
    CREATE TABLE IF NOT EXISTS pylovo.ways_result (
        version_id varchar(10) NOT NULL,
        clazz integer,
        source integer,
        target integer,
        cost double precision,
        reverse_cost double precision,
        geom geometry(LineString,{TARGET_EPSG}),
        way_id integer NOT NULL,
        plz integer,
        CONSTRAINT pk_ways_result PRIMARY KEY (version_id, way_id, plz),
        CONSTRAINT fk_ways_result_version_id_plz
            FOREIGN KEY (version_id, plz)
            REFERENCES pylovo.postcode_result (version_id, postcode_result_plz)
            ON DELETE CASCADE
    )
    """,
    "plz_parameters": """
    CREATE TABLE IF NOT EXISTS pylovo.plz_parameters (
        version_id varchar(10) NOT NULL,
        plz integer NOT NULL,
        trafo_num json,
        cable_length json,
        load_count_per_trafo json,
        bus_count_per_trafo json,
        sim_peak_load_per_trafo json,
        max_distance_per_trafo json,
        avg_distance_per_trafo json,
        CONSTRAINT parameters_pkey PRIMARY KEY (version_id, plz),
        CONSTRAINT fk_plz_parameters_version_id_plz
            FOREIGN KEY (version_id, plz)
            REFERENCES pylovo.postcode_result (version_id, postcode_result_plz)
            ON DELETE CASCADE
    )
    """,
    "res": """CREATE TABLE IF NOT EXISTS pylovo.res
                   (
                       osm_id     varchar PRIMARY KEY,
                       area       double precision,
                       use        varchar(80),
                       comment    varchar(80),
                       free_walls integer,
                       building_t varchar(80),
                       occupants  double precision,
                       floors     integer,
                       constructi varchar(80),
                       refurb_wal double precision,
                       refurb_roo double precision,
                       refurb_bas double precision,
                       refurb_win double precision,
                      geom       geometry(MultiPolygon, {TARGET_EPSG})
                   )
    """,
    "oth": """CREATE TABLE IF NOT EXISTS pylovo.oth
                               (
                                   osm_id     varchar PRIMARY KEY,
                                   area       double precision,
                                   use        varchar(80),
                                   comment    varchar(80),
                                   free_walls integer,
                                   geom       geometry(MultiPolygon, {TARGET_EPSG})
                               )
    """,
    "transformer_positions_with_grid": """
    DROP MATERIALIZED VIEW IF EXISTS pylovo.transformer_positions_with_grid CASCADE;
    CREATE OR REPLACE VIEW pylovo.transformer_positions_with_grid AS
        SELECT
            tp.*,
            gr.kcid,
            gr.bcid,
            gr.plz,
            gr.transformer_rated_power,
            gr.transformer_equipment_name,
            ed.s_max_kva,
            ed.max_i_a,
            ed.r_mohm_per_km,
            ed.x_mohm_per_km,
            ed.z_mohm_per_km,
            ed.cost_eur,
            ed.typ AS equipment_type
        FROM pylovo.transformer_positions tp
        JOIN pylovo.grid_result gr ON tp.grid_result_id = gr.grid_result_id
        LEFT JOIN pylovo.equipment_data ed
            ON gr.version_id = ed.version_id
            AND gr.transformer_equipment_name = ed.name
    """,
            "transformer_classified_with_grid": """
            CREATE MATERIALIZED VIEW IF NOT EXISTS pylovo.transformer_classified_with_grid AS (
        SELECT 
            tc.*,
            gr.version_id,
            gr.kcid,
            gr.bcid,
            gr.plz,
            gr.transformer_rated_power,
            gr.transformer_equipment_name,
            ed.s_max_kva,
            ed.max_i_a,
            ed.r_mohm_per_km,
            ed.x_mohm_per_km,
            ed.z_mohm_per_km,
            ed.cost_eur,
            ed.typ AS equipment_type
        FROM pylovo.transformer_classified tc
        JOIN pylovo.grid_result gr ON tc.grid_result_id = gr.grid_result_id
        LEFT JOIN pylovo.equipment_data ed 
            ON gr.version_id = ed.version_id 
            AND gr.transformer_equipment_name = ed.name
    );
            CREATE UNIQUE INDEX IF NOT EXISTS idx_transformer_classified_with_grid_uq_grid_result_id_classification_id
                ON pylovo.transformer_classified_with_grid (grid_result_id, classification_id);
            CREATE INDEX IF NOT EXISTS idx_transformer_classified_with_grid_geom ON pylovo.transformer_classified_with_grid USING gist (geom)
    """,
            "buildings_result_with_grid": """
            CREATE MATERIALIZED VIEW IF NOT EXISTS pylovo.buildings_result_with_grid AS (
        SELECT
            (br.version_id || '_' || br.objectid) AS result_uid,
            br.*,
            gr.kcid, gr.bcid, gr.plz
        FROM pylovo.buildings_result br
        JOIN pylovo.grid_result gr ON br.grid_result_id = gr.grid_result_id
    );
    CREATE UNIQUE INDEX IF NOT EXISTS idx_buildings_result_with_grid_uq_id
    ON pylovo.buildings_result_with_grid (result_uid);
    CREATE INDEX IF NOT EXISTS idx_buildings_result_with_grid_geom ON pylovo.buildings_result_with_grid USING gist (geom)
    """,


}

TEMP_CREATE_QUERIES = {
    "buildings_tem": """CREATE TABLE IF NOT EXISTS pylovo.buildings_tem
    (
        id integer,
        feature_id integer,
        objectid text,
        height double precision,
        floor_area double precision,
        floor_number integer,
        residential_floor_area double precision,
        nonresidential_floor_area double precision,
        nonresidential_use varchar(30),
        mix_score double precision,
        mix_rule text,
        mix_confidence text,
        building_use text,
        building_use_id text,
        building_type text,
        occupants integer,
        households integer,
        construction_year text,
        postcode integer,
        address_street_id bigint,
        street text,
        house_number text,
        geom geometry(Geometry,{TARGET_EPSG}),  -- needs to be geometry as multipoint & multipolygon get inserted here
        centroid geometry(Point,{TARGET_EPSG}),
        gemeindeschluessel text,
        changelog_id bigint,
        assigned_way_id text,
        type varchar(80),
        residential_peak_load_in_kw double precision,
        nonresidential_peak_load_in_kw double precision,
        nonresidential_mv_direct boolean NOT NULL DEFAULT false,
        peak_load_in_kw double precision,
        plz integer,
        vertice_id bigint,
        bcid integer,
        kcid integer,
        connection_point integer,
        agg_connection_point integer
    )""",
    "ways_tem": """CREATE TABLE IF NOT EXISTS pylovo.ways_tem
    (
        clazz integer,
        source integer,
        target integer,
        cost double precision,
        reverse_cost double precision,
        geom geometry(LineString,{TARGET_EPSG}),
        way_id integer,
        plz integer
    )""",
}

REFRESH_QUERIES = {
    "transformer_classified_with_grid": """
    REFRESH MATERIALIZED VIEW pylovo.transformer_classified_with_grid
    """,
    "buildings_result_with_grid": """
    REFRESH MATERIALIZED VIEW pylovo.buildings_result_with_grid
    """,
}

CREATE_QUERIES = {
    name: query.format(TARGET_EPSG=TARGET_EPSG)
    for name, query in CREATE_QUERIES.items()
}

TEMP_CREATE_QUERIES = {
    name: query.format(TARGET_EPSG=TARGET_EPSG)
    for name, query in TEMP_CREATE_QUERIES.items()
}