"""Sphinx configuration for the pylovo documentation.

Build locally from the repository root::

    uv sync --extra docs
    uv run sphinx-build -W --keep-going -b html docs/source docs/build/html

The API reference is generated by sphinx-autoapi, which parses ``src/pylovo``
statically. Neither a database nor a ``.env`` file is needed to build the docs.
With ``-W`` every warning fails the build, including docstring errors in the
generated API pages.
"""
from __future__ import annotations

import tomllib
from pathlib import Path

DOCS_SOURCE = Path(__file__).resolve().parent
REPO_ROOT = DOCS_SOURCE.parents[1]

with open(REPO_ROOT / "pyproject.toml", "rb") as handle:
    _project_metadata = tomllib.load(handle)["project"]

# -- Project information -----------------------------------------------------
project = "pylovo"
author = "Beneharo Reveron Baecker and contributors"
copyright = "2023-2026, TUM ENS"
release = _project_metadata["version"]
version = ".".join(release.split(".")[:2])

# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "sphinx_copybutton",
    "sphinx_design",
    "autoapi.extension",
]

exclude_patterns = ["_build", "build"]
language = "en"
nitpicky = False

# Google-style docstrings (Args:, Returns:, Raises:)
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_use_rtype = False
napoleon_use_ivar = True  # "Attributes:" as fields; avoids duplicates with autoapi's attribute entries

# -- sphinx-autoapi ----------------------------------------------------------
autoapi_type = "python"
autoapi_dirs = [str(REPO_ROOT / "src" / "pylovo")]
autoapi_root = "api"
autoapi_add_toctree_entry = False
autoapi_keep_files = False
autoapi_member_order = "groupwise"
autoapi_python_class_content = "both"
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
]
# The classification and validation modules are not part of this documentation.
autoapi_ignore = [
    "*/classification/*",
    "*/plotting/classification/*",
    "*/plotting/validation/*",
    "*/cli/classify.py",
    "*/analysis/validation_helpers.py",
    "*/__pycache__/*",
]

# autoapi parses statically and cannot follow names that config_loader defines inside an
# ``if`` block (the INFDB_* settings); that is a limitation of the tool, not an error.
suppress_warnings = ["autoapi.python_import_resolution"]

# -- Copy button -------------------------------------------------------------
copybutton_prompt_text = r"\$ "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = False

# -- HTML output -------------------------------------------------------------
html_theme = "furo"
html_title = f"pylovo {release}"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_logo = "images/logo.png"
html_favicon = None
html_show_sourcelink = False
html_theme_options = {
    "source_repository": "https://github.com/tum-ens/pylovo/",
    "source_branch": "main",
    "source_directory": "docs/source/",
    "navigation_with_keys": True,
    "sidebar_hide_name": True,
}

# -- LaTeX / PDF output ------------------------------------------------------
latex_documents = [("index", "pylovo.tex", "pylovo documentation", author, "manual")]
latex_elements = {
    "papersize": "a4paper",
    # Characters that pdflatex does not know by default.
    "preamble": r"""
\DeclareUnicodeCharacter{2308}{\ensuremath{\lceil}}
\DeclareUnicodeCharacter{2309}{\ensuremath{\rceil}}
\DeclareUnicodeCharacter{03C6}{\ensuremath{\varphi}}
\DeclareUnicodeCharacter{03A9}{\ensuremath{\Omega}}
\DeclareUnicodeCharacter{207B}{\ensuremath{^{-}}}
\DeclareUnicodeCharacter{2713}{\ensuremath{\checkmark}}
""",
}


# -- Hooks -------------------------------------------------------------------
_SEEN_MODULE_DATA: set[str] = set()


def _skip_duplicate_module_data(app, what, name, obj, skip, options):
    """Document a module-level name only once if it is assigned twice (e.g. CREATE_QUERIES)."""
    if what == "data":
        if name in _SEEN_MODULE_DATA:
            return True
        _SEEN_MODULE_DATA.add(name)
    return skip


def setup(app):
    app.connect("autoapi-skip-member", _skip_duplicate_module_data)
