import yaml
import os
import pandas as pd
from dotenv import load_dotenv, find_dotenv

def load_yaml_config(filepath: str):
    """Loads a YAML configuration file."""
    abs_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), filepath)
    
    if not os.path.exists(abs_path):
        raise FileNotFoundError(f"Config file not found: {abs_path}")
    
    with open(abs_path, "r", encoding="utf-8") as file:
        return yaml.safe_load(file)

# Load Project Root
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Load all configurations with correct paths
CONFIG_DATA = load_yaml_config("../config/config_data.yaml")
CONFIG_VERSION = load_yaml_config("../config/config_version.yaml")
CONFIG_CLASSIFICATION = load_yaml_config("../config/config_classification.yaml")
CONFIG_CLUSTERING = load_yaml_config("../config/config_clustering.yaml")

# Load database connection configuration from CONFIG_DATA
load_dotenv(find_dotenv(), override=True)
DBNAME = os.getenv("DBNAME", CONFIG_DATA["DBNAME"])
USER = os.getenv("USER", CONFIG_DATA["USER"])
HOST = os.getenv("HOST", CONFIG_DATA["HOST"])
PORT = os.getenv("PORT", CONFIG_DATA["PORT"])
PASSWORD = os.getenv("PASSWORD", CONFIG_DATA["PASSWORD"])
TARGET_SCHEMA = os.getenv("TARGET_SCHEMA", CONFIG_DATA["TARGET_SCHEMA"])

USE_INFDB = True if CONFIG_DATA["USE_INFDB"] in [True, "True", "true", 1, "1", "on"] else False
INFDB_DBNAME = os.getenv("INFDB_DBNAME", "not set")
INFDB_USER = os.getenv("INFDB_USER", "not set")
INFDB_HOST = os.getenv("INFDB_HOST", "not set")
INFDB_PORT = os.getenv("INFDB_PORT", "not set")
INFDB_PASSWORD = os.getenv("INFDB_PASSWORD", "not set")
INFDB_SOURCE_SCHEMA = os.getenv("INFDB_SOURCE_SCHEMA", "public")

# Assign other variables from CONFIG_DATA
RESULT_DIR = os.path.join(os.getcwd(), "results")
ANALYZE_GRIDS = CONFIG_DATA["ANALYZE_GRIDS"]
SAVE_GRID_FOLDER = CONFIG_DATA["SAVE_GRID_FOLDER"]
LOG_LEVEL = CONFIG_DATA["LOG_LEVEL"]
N_JOBS_PERCENTAGE = CONFIG_DATA.get("N_JOBS_PERCENTAGE", 50)
K_MEANS_SEED = CONFIG_DATA["K_MEANS_SEED"]
CLUSTERING_PARAMETERS = CONFIG_DATA["CLUSTERING_PARAMETERS"]
MUNICIPAL_REGISTER = CONFIG_DATA["MUNICIPAL_REGISTER"]
CSV_FILE_LIST = [
    {"path": os.path.join("raw_data", "equipment_data.csv"), "table_name": "equipment_data"},
    {"path": os.path.join("raw_data", "postcode.csv"), "table_name": "postcode"},]
CSV_FILE_LIST_INFDB = [
    {"path": os.path.join("raw_data", "equipment_data.csv"), "table_name": "equipment_data"},]

# Assign all variables from CONFIG_VERSION
VERSION_ID = CONFIG_VERSION["VERSION_ID"]
VERSION_COMMENT = CONFIG_VERSION["VERSION_COMMENT"]
PLOT_COLOR_DICT = CONFIG_VERSION["PLOT_COLOR_DICT"]
CONNECTION_AVAILABLE_CABLES = CONFIG_VERSION["CONNECTION_AVAILABLE_CABLES"]
CABLE_COST_DICT = CONFIG_VERSION["CABLE_COST_DICT"]
SIM_FACTOR = CONFIG_VERSION["SIM_FACTOR"]
PEAK_LOAD_HOUSEHOLD = CONFIG_VERSION["PEAK_LOAD_HOUSEHOLD"]
CONSUMER_CATEGORIES = pd.DataFrame(CONFIG_VERSION["CONSUMER_CATEGORIES"])
LARGE_COMPONENT_LOWER_BOUND = CONFIG_VERSION["LARGE_COMPONENT_LOWER_BOUND"]
LARGE_COMPONENT_DIVIDER = CONFIG_VERSION["LARGE_COMPONENT_DIVIDER"]
VN = CONFIG_VERSION["VN"]
V_BAND_LOW = CONFIG_VERSION["V_BAND_LOW"]
V_BAND_HIGH = CONFIG_VERSION["V_BAND_HIGH"]

# Assign all variables from CONFIG_CLASSIFICATION
CLASSIFICATION_VERSION = CONFIG_CLASSIFICATION["CLASSIFICATION_VERSION"]
CLASSIFICATION_VERSION_COMMENT = CONFIG_CLASSIFICATION["CLASSIFICATION_VERSION_COMMENT"]
CLASSIFICATION_REGION = CONFIG_CLASSIFICATION["CLASSIFICATION_REGION"]
NO_OF_CLUSTERS_ALLOWED = CONFIG_CLASSIFICATION["NO_OF_CLUSTERS_ALLOWED"]
N_SAMPLES = CONFIG_CLASSIFICATION["N_SAMPLES"]
REGION_DICT = CONFIG_CLASSIFICATION["REGION_DICT"]
REGIOSTAR7_DICT = CONFIG_CLASSIFICATION["REGIOSTAR7_DICT"]
REGIO7_REGIO5_GEM_DICT = CONFIG_CLASSIFICATION["REGIO7_REGIO5_GEM_DICT"]

# Assign all variables from CONFIG_CLUSTERING
LIST_OF_CLUSTERING_PARAMETERS = CONFIG_CLUSTERING["LIST_OF_CLUSTERING_PARAMETERS"]
N_CLUSTERS_KMEDOID = CONFIG_CLUSTERING["N_CLUSTERS_KMEDOID"]
N_CLUSTERS_KMEANS = CONFIG_CLUSTERING["N_CLUSTERS_KMEANS"]
N_CLUSTERS_GMM = CONFIG_CLUSTERING["N_CLUSTERS_GMM"]
THRESHOLD_MAX_TRAFO_DIS = CONFIG_CLUSTERING["THRESHOLD_MAX_TRAFO_DIS"]
THRESHOLD_HOUSEHOLDS_PER_BUILDING = CONFIG_CLUSTERING["THRESHOLD_HOUSEHOLDS_PER_BUILDING"]

# Thresholds for clustering parameters
THRESHOLD_AVG_TRAFO_DIS = CONFIG_CLUSTERING["THRESHOLD_AVG_TRAFO_DIS"]
THRESHOLD_NO_HOUSE_CONNECTIONS = CONFIG_CLUSTERING["THRESHOLD_NO_HOUSE_CONNECTIONS"]
THRESHOLD_VSW_PER_BRANCH = CONFIG_CLUSTERING["THRESHOLD_VSW_PER_BRANCH"]
THRESHOLD_NO_HOUSEHOLDS = CONFIG_CLUSTERING["THRESHOLD_NO_HOUSEHOLDS"]